# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'

target '99' do
  # Comment the next line if you don't want to use dynamic frameworks
  use_frameworks!
    pod 'SDWebImage'
  # Pods for 99

  target '99Tests' do
    inherit! :search_paths
    # Pods for testing
  end

  target '99UITests' do
    # Pods for testing
  end

end
